import { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, ChevronDown, FlaskConical } from 'lucide-react';
import { lessons, patterns } from '../content/registry';
import type { Exercise, PatternExercise } from '../core/types';
import { ExercisePanel } from './ExercisePanel';
import { Button } from '../components/ui/button';
type Row={exercise:Exercise|PatternExercise;sourceLabel:string;patternMode:boolean;ownerKind:'lesson'|'pattern';ownerId:string};
const FILTERS=[{key:'recognition',label:'Recognition (mixed)',kind:'choose-approach'},{key:'predict',label:'Predict state',kind:'predict-state'},{key:'complete',label:'Complete code',kind:'complete-code'},{key:'debug',label:'Fix a bug',kind:'fix-mistake'},{key:'write',label:'Write a solution',kind:'write-solution'},{key:'all',label:'All',kind:null}];
const PAGE_SIZE=20;
const uid=(row:Row)=>`${row.ownerKind}:${row.ownerId}:${row.exercise.id}`;
export function Practice(){
 const [filter,setFilter]=useState('recognition');const [page,setPage]=useState(0);const [selected,setSelected]=useState<string>();const [opened,setOpened]=useState(new Set<string>());
 const rows:Row[]=useMemo(()=>[...lessons.flatMap(l=>l.exercises.map(exercise=>({exercise,sourceLabel:l.title,patternMode:false,ownerKind:'lesson' as const,ownerId:l.id}))),...patterns.flatMap(p=>p.exercises.map(exercise=>({exercise,sourceLabel:p.title,patternMode:true,ownerKind:'pattern' as const,ownerId:p.id})))],[]);
 const active=FILTERS.find(f=>f.key===filter)??FILTERS[0];const matching=rows.filter(r=>active.kind===null||r.exercise.kind===active.kind);const pages=Math.max(1,Math.ceil(matching.length/PAGE_SIZE));const index=Math.min(page,pages-1);const start=index*PAGE_SIZE;const shown=matching.slice(start,start+PAGE_SIZE);const chosen=selected??(shown[0]?uid(shown[0]):undefined);
 const move=(next:number)=>{setPage(next);setSelected(undefined);setOpened(new Set());};
 const select=(id:string)=>{setSelected(chosen===id?'':id);setOpened(before=>new Set([...before,id,...(chosen?[chosen]:[])]));};
 return <main id="main-content" className="practice-page catalog-page"><div className="eyebrow">A LITTLE PRACTICE, A DEEPER UNDERSTANDING</div><h1>Make the idea your own.</h1><p className="page-description">Predict, experiment, debug, and explain. Small steps count.</p><div className="practice-filters" aria-label="Exercise types">{FILTERS.map(f=><Button key={f.key} variant={filter===f.key?'default':'outline'} onClick={()=>{setFilter(f.key);move(0);}}>{f.label}</Button>)}</div><div className="practice-summary"><FlaskConical size={20}/><div><strong>{active.label}</strong><p>{filter==='recognition'?'The source topic is hidden. Choose an approach and the conditions that make it work.':'Try the starter, use progressive hints, and check your reasoning.'}</p></div><span>{matching.length} exercises</span></div><nav className="practice-pager" aria-label="Practice pages"><Button variant="outline" size="sm" onClick={()=>move(Math.max(0,index-1))} disabled={index===0}><ArrowLeft/>Previous</Button><span>Showing {matching.length?start+1:0}–{Math.min(start+PAGE_SIZE,matching.length)} of {matching.length} · page {index+1} of {pages}</span><Button variant="outline" size="sm" onClick={()=>move(Math.min(pages-1,index+1))} disabled={index===pages-1}>Next<ArrowRight/></Button></nav><div className="challenge-list">{shown.map((row,i)=>{const id=uid(row);const expanded=chosen===id;const mounted=expanded||opened.has(id);return <section className={'challenge-item '+(expanded?'is-expanded':'')} key={id}><button className="challenge-heading" aria-expanded={expanded} aria-controls={'challenge-'+id} onClick={()=>select(id)}><span className="challenge-number">{String(start+i+1).padStart(2,'0')}</span><span><strong>{filter==='recognition'?`Recognition challenge ${start+i+1}`:row.sourceLabel}</strong><small>{row.exercise.kind.replaceAll('-',' ')}</small></span><ChevronDown size={18}/></button><div id={'challenge-'+id} hidden={!expanded}>{mounted&&<ExercisePanel exercise={row.exercise} patternMode={row.patternMode} ownerKind={row.ownerKind} ownerId={row.ownerId}/>}</div></section>})}</div></main>;
}
