/**
 * R5.3 — human semantic-review ledger (GENERATED by scripts/gen_review_ledger.mjs,
 * run deliberately by a human after re-reading the items).
 *
 * Each entry records that a person read this item's teaching content at the exact
 * `reviewedHash`. Evidence granting (codemod_add_evidence.mjs) sets
 * `evidence.semanticReview: true` ONLY when the item's CURRENT content hash
 * equals `reviewedHash` here — so a later content edit (which changes the hash)
 * makes semanticReview revert to pending until the item is re-read and this
 * ledger is regenerated. This is a RECORDED HUMAN CLAIM; the automated tests do
 * not "prove" the reading happened, they only enforce that a claim cannot outlive
 * the content it was made against.
 */
export interface ReviewLedgerEntry {
  id: string;
  kind: "lesson" | "pattern";
  /** contentHashOf(item) at the moment of human review. */
  reviewedHash: string;
  reviewedAt: string;
  /** R5.3 review batch (1-6). */
  batch: number;
}

export const REVIEW_LEDGER: ReviewLedgerEntry[] = [
  {
    "id": "adjacency-lists",
    "kind": "lesson",
    "reviewedHash": "7f68c2c7ebc515cc",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "amortized",
    "kind": "lesson",
    "reviewedHash": "ce94e80ff544fa4f",
    "reviewedAt": "2026-09-20",
    "batch": 1
  },
  {
    "id": "anagrams",
    "kind": "lesson",
    "reviewedHash": "b12a78a25235425e",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "array-traversal",
    "kind": "lesson",
    "reviewedHash": "f616daf8c6cd1672",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "avl-rotations",
    "kind": "lesson",
    "reviewedHash": "adeb4dcb3fff93c5",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "bellman-ford",
    "kind": "lesson",
    "reviewedHash": "3d50c4a7c359763c",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "bfs-queues",
    "kind": "lesson",
    "reviewedHash": "a2ce1fbf3a6e289b",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "binary-search",
    "kind": "lesson",
    "reviewedHash": "858676ebe239736a",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "binary-search-answer",
    "kind": "lesson",
    "reviewedHash": "4d882f930f6d95d4",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "bit-check-set-clear",
    "kind": "lesson",
    "reviewedHash": "26f65c64c99c9b43",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "bit-logical-ops",
    "kind": "lesson",
    "reviewedHash": "45ff320caba8429c",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "bit-shifts",
    "kind": "lesson",
    "reviewedHash": "790ea4afc87d7ed1",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "bounds",
    "kind": "lesson",
    "reviewedHash": "edecf44dc364f302",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "bst-operations",
    "kind": "lesson",
    "reviewedHash": "621da21591ad3de3",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "bubble-sort",
    "kind": "lesson",
    "reviewedHash": "52c4327b96e4414f",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "bucket-sort",
    "kind": "lesson",
    "reviewedHash": "309dedebdb8017e4",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "caching-seen",
    "kind": "lesson",
    "reviewedHash": "e6176608e19165d1",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "cases",
    "kind": "lesson",
    "reviewedHash": "3071b09105a0b4fe",
    "reviewedAt": "2026-09-20",
    "batch": 1
  },
  {
    "id": "classes",
    "kind": "lesson",
    "reviewedHash": "21447fd00300d564",
    "reviewedAt": "2026-09-20",
    "batch": 1
  },
  {
    "id": "comparators",
    "kind": "lesson",
    "reviewedHash": "9d38dedfe3c0ac31",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "complexity",
    "kind": "lesson",
    "reviewedHash": "e8a0d4d6d10a6c0b",
    "reviewedAt": "2026-09-20",
    "batch": 1
  },
  {
    "id": "conditions",
    "kind": "lesson",
    "reviewedHash": "6c798609f0518c64",
    "reviewedAt": "2026-09-20",
    "batch": 1
  },
  {
    "id": "connected-components",
    "kind": "lesson",
    "reviewedHash": "2f833866cd25c402",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "correctness",
    "kind": "lesson",
    "reviewedHash": "76121f369b7dcc0c",
    "reviewedAt": "2026-09-20",
    "batch": 1
  },
  {
    "id": "count-set-bits",
    "kind": "lesson",
    "reviewedHash": "1eb24d36b17f395d",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "counting-sort",
    "kind": "lesson",
    "reviewedHash": "366a8d4778374e38",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "dijkstra",
    "kind": "lesson",
    "reviewedHash": "daa83e77d9ad9981",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "dp-1d-2d",
    "kind": "lesson",
    "reviewedHash": "c0322a7aa8f75947",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-backtracking",
    "kind": "lesson",
    "reviewedHash": "f45dfe337744e8d1",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-base-cases",
    "kind": "lesson",
    "reviewedHash": "50f8db5a407a2386",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-climbing-stairs",
    "kind": "lesson",
    "reviewedHash": "da18e0dc3179927d",
    "reviewedAt": "2026-09-21",
    "batch": 6
  },
  {
    "id": "dp-coin-change",
    "kind": "lesson",
    "reviewedHash": "6a4b7dc2fc0c141a",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-combinations",
    "kind": "lesson",
    "reviewedHash": "728b4e6f50b0a001",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-divide-and-conquer",
    "kind": "lesson",
    "reviewedHash": "60b2b686e927ece5",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-grid-paths",
    "kind": "lesson",
    "reviewedHash": "5ae3491ae702ef5f",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-house-robber",
    "kind": "lesson",
    "reviewedHash": "418441b9c60bf081",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-knapsack",
    "kind": "lesson",
    "reviewedHash": "d78b986ca8eb438e",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-lcs",
    "kind": "lesson",
    "reviewedHash": "cd8a47388ef49f98",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-lis",
    "kind": "lesson",
    "reviewedHash": "09fda4bb9f74739d",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-memoization",
    "kind": "lesson",
    "reviewedHash": "3be2a477955dc070",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-n-queens",
    "kind": "lesson",
    "reviewedHash": "e4110d6cb8a37817",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-permutations",
    "kind": "lesson",
    "reviewedHash": "bad1d9f45bfeb32a",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-recursive-calls",
    "kind": "lesson",
    "reviewedHash": "7ff86b664bf2e25c",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-state-transitions",
    "kind": "lesson",
    "reviewedHash": "9e4facb93c49195a",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-subsequences",
    "kind": "lesson",
    "reviewedHash": "1a4727e017c902bc",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-subsets",
    "kind": "lesson",
    "reviewedHash": "b602aea1318dabb9",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-tabulation",
    "kind": "lesson",
    "reviewedHash": "83adced1c625a49a",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "duplicate-detection",
    "kind": "lesson",
    "reviewedHash": "6aee44733fc5647b",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "errors",
    "kind": "lesson",
    "reviewedHash": "ebcb0f13434b9c81",
    "reviewedAt": "2026-09-20",
    "batch": 1
  },
  {
    "id": "expression-evaluation",
    "kind": "lesson",
    "reviewedHash": "b7bfb5e829ac0a3c",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "expressions",
    "kind": "lesson",
    "reviewedHash": "f468a4884157f52b",
    "reviewedAt": "2026-09-20",
    "batch": 1
  },
  {
    "id": "fenwick-tree",
    "kind": "lesson",
    "reviewedHash": "d8c35612ca1fa2da",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "floyd-warshall",
    "kind": "lesson",
    "reviewedHash": "4e91454e6ba0b498",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "functions",
    "kind": "lesson",
    "reviewedHash": "7d799d6d7e822e95",
    "reviewedAt": "2026-09-20",
    "batch": 1
  },
  {
    "id": "graph-bfs",
    "kind": "lesson",
    "reviewedHash": "811f24f1f6600b3d",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "graph-cycle-detection",
    "kind": "lesson",
    "reviewedHash": "20404691a974a7c3",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "graph-dfs",
    "kind": "lesson",
    "reviewedHash": "9652c3ab9322257b",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "graph-representations",
    "kind": "lesson",
    "reviewedHash": "5171166c687dd224",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "grouping",
    "kind": "lesson",
    "reviewedHash": "ffb83aa3cdf61059",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "hashing-frequency",
    "kind": "lesson",
    "reviewedHash": "60952d2af4740c9d",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "heap-sift",
    "kind": "lesson",
    "reviewedHash": "a5b7db93c08fb145",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "heap-sort",
    "kind": "lesson",
    "reviewedHash": "04b645b046888e1f",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "in-place-modification",
    "kind": "lesson",
    "reviewedHash": "a2df1a265529b0c1",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "insertion-sort",
    "kind": "lesson",
    "reviewedHash": "ca9b001787731a5c",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "interval-sorting",
    "kind": "lesson",
    "reviewedHash": "513f8dd67a2dc080",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "intervals",
    "kind": "lesson",
    "reviewedHash": "c8e094528cb87a81",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "io",
    "kind": "lesson",
    "reviewedHash": "6f85c9e72a228543",
    "reviewedAt": "2026-09-20",
    "batch": 1
  },
  {
    "id": "kadane",
    "kind": "lesson",
    "reviewedHash": "aaf71317c6005d87",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "kmp",
    "kind": "lesson",
    "reviewedHash": "446d68e0a7001797",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "kruskal",
    "kind": "lesson",
    "reviewedHash": "e3dbeae2bcc7dcb9",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "kth-largest",
    "kind": "lesson",
    "reviewedHash": "df0d6174cd1d4269",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "linear-search",
    "kind": "lesson",
    "reviewedHash": "e5deba3966b36eae",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "linked-list-cycle-detection",
    "kind": "lesson",
    "reviewedHash": "e3a452a6d8c59008",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "linked-list-deques",
    "kind": "lesson",
    "reviewedHash": "51ed8899310a33e7",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "linked-list-dummy-nodes",
    "kind": "lesson",
    "reviewedHash": "48c4dd2c6e4b4662",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "linked-list-merging",
    "kind": "lesson",
    "reviewedHash": "59f1efab7036d3f8",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "linked-list-middle",
    "kind": "lesson",
    "reviewedHash": "2d52848498c4f4e2",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "linked-list-pointer-manipulation",
    "kind": "lesson",
    "reviewedHash": "01743459a398036c",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "linked-list-reversal",
    "kind": "lesson",
    "reviewedHash": "857315a8c745ea34",
    "reviewedAt": "2026-09-21",
    "batch": 4
  },
  {
    "id": "linked-list-slow-fast",
    "kind": "lesson",
    "reviewedHash": "362e77924370cd15",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "linked-list-traversal",
    "kind": "lesson",
    "reviewedHash": "b8eea42d6735a88f",
    "reviewedAt": "2026-09-21",
    "batch": 4
  },
  {
    "id": "linked-list-variants",
    "kind": "lesson",
    "reviewedHash": "9b42c27282fa4e5a",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "loops",
    "kind": "lesson",
    "reviewedHash": "fcadc9eb125d967c",
    "reviewedAt": "2026-10-04",
    "batch": 1
  },
  {
    "id": "lowest-common-ancestor",
    "kind": "lesson",
    "reviewedHash": "1354410f680a391d",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "maps-sets",
    "kind": "lesson",
    "reviewedHash": "661c4d8cff1ea841",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "matrix-search",
    "kind": "lesson",
    "reviewedHash": "eec14557b61b2f6a",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "matrix-traversal",
    "kind": "lesson",
    "reviewedHash": "ddc73b7d60517a2b",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "merge-sort",
    "kind": "lesson",
    "reviewedHash": "458cbc7314588dfb",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "merge-sorted-data",
    "kind": "lesson",
    "reviewedHash": "cebf06d98c187c83",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "min-max-heaps",
    "kind": "lesson",
    "reviewedHash": "92fff25d8392e6cb",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "min-max-tracking",
    "kind": "lesson",
    "reviewedHash": "2574f926717eb8f3",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "monotonic-stack",
    "kind": "lesson",
    "reviewedHash": "2798e6cda01da93a",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "multi-source-bfs",
    "kind": "lesson",
    "reviewedHash": "fb978bd14a94836d",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "palindromes",
    "kind": "lesson",
    "reviewedHash": "ac37883cb5daa819",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "parentheses-matching",
    "kind": "lesson",
    "reviewedHash": "ac8bf5cbb2887d67",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "prefix-search",
    "kind": "lesson",
    "reviewedHash": "cbb946da658a13ec",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "prefix-sums",
    "kind": "lesson",
    "reviewedHash": "92a7f8ab934d6310",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "prefix-sums-map",
    "kind": "lesson",
    "reviewedHash": "f8d7f87c48b5cee9",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "prim",
    "kind": "lesson",
    "reviewedHash": "f8f767d2d2b389fb",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "quick-sort",
    "kind": "lesson",
    "reviewedHash": "6ddeedabb64ddfc0",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "radix-sort",
    "kind": "lesson",
    "reviewedHash": "e07f1331233791ca",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "references-mutation",
    "kind": "lesson",
    "reviewedHash": "bdfd71de6dbf2fdf",
    "reviewedAt": "2026-09-20",
    "batch": 1
  },
  {
    "id": "representations",
    "kind": "lesson",
    "reviewedHash": "c8890b6f2e543964",
    "reviewedAt": "2026-09-20",
    "batch": 1
  },
  {
    "id": "rotated-array-search",
    "kind": "lesson",
    "reviewedHash": "2363c807562f89ee",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "running-median",
    "kind": "lesson",
    "reviewedHash": "32b6550144481f53",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "scope",
    "kind": "lesson",
    "reviewedHash": "fa66cb266bc57f18",
    "reviewedAt": "2026-09-20",
    "batch": 1
  },
  {
    "id": "segment-tree",
    "kind": "lesson",
    "reviewedHash": "d48da2f9cd658834",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "selection-sort",
    "kind": "lesson",
    "reviewedHash": "367a32685f5d8fdb",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "shortest-paths-unweighted",
    "kind": "lesson",
    "reviewedHash": "cf7f9d2070eb5686",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "sliding-window",
    "kind": "lesson",
    "reviewedHash": "74bfa7e672eeddf1",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "stack-queue-operations",
    "kind": "lesson",
    "reviewedHash": "c5524ee01c9035cd",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "string-frequency",
    "kind": "lesson",
    "reviewedHash": "b5e9d6c9b83f14e6",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "string-parsing",
    "kind": "lesson",
    "reviewedHash": "a93ae24bc0c537f6",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "string-sliding-window",
    "kind": "lesson",
    "reviewedHash": "e7a511cafe0e3e6d",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "string-two-pointers",
    "kind": "lesson",
    "reviewedHash": "3f515bb6c7e7b375",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "substrings",
    "kind": "lesson",
    "reviewedHash": "33af0854d68ef359",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "top-k",
    "kind": "lesson",
    "reviewedHash": "3af0a2f3e28f1dd2",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "topological-sort",
    "kind": "lesson",
    "reviewedHash": "f078941e3f9246a4",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "tree-bfs",
    "kind": "lesson",
    "reviewedHash": "4df7d7c7e37958ea",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "tree-construction",
    "kind": "lesson",
    "reviewedHash": "bb8c7942898c6a9c",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "tree-dfs",
    "kind": "lesson",
    "reviewedHash": "4947b5aa1f04029a",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "tree-height-depth",
    "kind": "lesson",
    "reviewedHash": "da2e86bc77664c94",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "tree-traversals",
    "kind": "lesson",
    "reviewedHash": "dd8bc80e7dd6d71d",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "trie-insertion",
    "kind": "lesson",
    "reviewedHash": "6b038b720dd891ab",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "two-heap-pattern",
    "kind": "lesson",
    "reviewedHash": "84cd0aadc15180e9",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "two-pointers",
    "kind": "lesson",
    "reviewedHash": "cf4bae0c98ce3962",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "union-find",
    "kind": "lesson",
    "reviewedHash": "48d6312f36de86b2",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "value-to-index",
    "kind": "lesson",
    "reviewedHash": "542d8d931571f5bc",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "variables-and-types",
    "kind": "lesson",
    "reviewedHash": "612fac88ec9babef",
    "reviewedAt": "2026-10-04",
    "batch": 1
  },
  {
    "id": "word-search",
    "kind": "lesson",
    "reviewedHash": "ba9d6414cb6089f8",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "xor-cancellation",
    "kind": "lesson",
    "reviewedHash": "a9b1f265718677d1",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "backtracking",
    "kind": "pattern",
    "reviewedHash": "bc29d040d44e7170",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "bfs-shortest-path",
    "kind": "pattern",
    "reviewedHash": "957e7deb189901c7",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "binary-search-on-answer",
    "kind": "pattern",
    "reviewedHash": "45469c50d2ddd812",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "bitwise-xor",
    "kind": "pattern",
    "reviewedHash": "f6df2c04e6e7ce62",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "cyclic-sort",
    "kind": "pattern",
    "reviewedHash": "ed13dda9854c0181",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "dijkstra",
    "kind": "pattern",
    "reviewedHash": "3a5b31d46b111b11",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "divide-and-conquer",
    "kind": "pattern",
    "reviewedHash": "de7f5335e2cae7e4",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "dynamic-programming",
    "kind": "pattern",
    "reviewedHash": "b7dee1b0b8f39abf",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "fast-slow-pointers",
    "kind": "pattern",
    "reviewedHash": "e41303f85cbcd3c4",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "graph-dfs-components",
    "kind": "pattern",
    "reviewedHash": "9c61dcbd0bf61b54",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "greedy-interval-scheduling",
    "kind": "pattern",
    "reviewedHash": "ce6a9d1806261ecb",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "in-place-linkedlist-reversal",
    "kind": "pattern",
    "reviewedHash": "8ef3ef9cc48bd3e7",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "k-way-merge",
    "kind": "pattern",
    "reviewedHash": "989d9ee9833ddc7d",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "kadane",
    "kind": "pattern",
    "reviewedHash": "efd782e62a56c770",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "knapsack",
    "kind": "pattern",
    "reviewedHash": "7749c49d19d34a6b",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "matrix-traversal",
    "kind": "pattern",
    "reviewedHash": "ecea1e62a727d0d0",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "merge-intervals",
    "kind": "pattern",
    "reviewedHash": "83d1682bc2616fd2",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "modified-binary-search",
    "kind": "pattern",
    "reviewedHash": "2cabd34ad69274cf",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "monotonic-stack",
    "kind": "pattern",
    "reviewedHash": "7687976eed941da5",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "prefix-sums-hashmap",
    "kind": "pattern",
    "reviewedHash": "178e7f330fe6c912",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "sliding-window",
    "kind": "pattern",
    "reviewedHash": "39e48720198beaab",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "top-k-heap",
    "kind": "pattern",
    "reviewedHash": "36205da1f8844db0",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "topological-sort",
    "kind": "pattern",
    "reviewedHash": "573ff3d71ec011ad",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "tree-bfs",
    "kind": "pattern",
    "reviewedHash": "ca33adc64ede7837",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "tree-dfs",
    "kind": "pattern",
    "reviewedHash": "ae4607ac6aa41ef3",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "trie-prefix",
    "kind": "pattern",
    "reviewedHash": "105ec245df12260e",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "two-heaps",
    "kind": "pattern",
    "reviewedHash": "e9fd943134a8ecc2",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "two-pointers",
    "kind": "pattern",
    "reviewedHash": "c81867b731e0b97f",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "union-find",
    "kind": "pattern",
    "reviewedHash": "85f85239d7e426d1",
    "reviewedAt": "2026-09-20",
    "batch": 5
  }
];

/** Keyed by "<kind>:<id>" because a lesson and a pattern can share an id
 * (e.g. two-pointers, sliding-window, kadane, tree-dfs, dijkstra, ...). */
export const REVIEW_LEDGER_BY_KEY: Map<string, ReviewLedgerEntry> = new Map(
  REVIEW_LEDGER.map((e) => [e.kind + ":" + e.id, e]),
);
