/**
 * Semantic-review ledger (GENERATED by scripts/gen_review_ledger.mjs after review).
 * Reviews may be human or explicitly human-delegated technical-agent reviews.
 *
 * Each entry records review of this item's teaching content at the exact
 * `reviewedHash`. Evidence granting (codemod_add_evidence.mjs) sets
 * `evidence.semanticReview: true` ONLY when the item's CURRENT content hash
 * equals `reviewedHash` here — so a later content edit (which changes the hash)
 * makes semanticReview revert to pending until the item is re-read and this
 * ledger is regenerated. This is a RECORDED REVIEW CLAIM; the automated tests do
 * not "prove" the reading happened, they only enforce that a claim cannot outlive
 * the content it was made against.
 */
export interface ReviewLedgerEntry {
  id: string;
  kind: "lesson" | "pattern";
  /** contentHashOf(item) at the moment of human review. */
  reviewedHash: string;
  reviewedAt: string;
  /** Optional provenance. Older entries are preserved verbatim. */
  reviewer?: string;
  reviewerKind?: "human" | "delegated-agent";
  /** R5.3 review batch (1-6). */
  batch: number;
}

export const REVIEW_LEDGER: ReviewLedgerEntry[] = [
  {
    "id": "adjacency-lists",
    "kind": "lesson",
    "reviewedHash": "701532f135396d6c",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "amortized",
    "kind": "lesson",
    "reviewedHash": "eb623945ef0610d5",
    "reviewedAt": "2026-10-05",
    "batch": 1
  },
  {
    "id": "anagrams",
    "kind": "lesson",
    "reviewedHash": "0eba2489bd20916a",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "array-traversal",
    "kind": "lesson",
    "reviewedHash": "e074694311042558",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "avl-rotations",
    "kind": "lesson",
    "reviewedHash": "378517a19ceb2355",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "bellman-ford",
    "kind": "lesson",
    "reviewedHash": "107ddf63e222902a",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "bfs-queues",
    "kind": "lesson",
    "reviewedHash": "2e245216518b3f20",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "binary-search",
    "kind": "lesson",
    "reviewedHash": "1d031e5c33e0ad94",
    "reviewedAt": "2026-10-10",
    "batch": 3,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "binary-search-answer",
    "kind": "lesson",
    "reviewedHash": "f6a9654b672ca67a",
    "reviewedAt": "2026-10-10",
    "batch": 3,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "bit-check-set-clear",
    "kind": "lesson",
    "reviewedHash": "db9506e3e4e13134",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "bit-logical-ops",
    "kind": "lesson",
    "reviewedHash": "f0a77f6b1719bed3",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "bit-shifts",
    "kind": "lesson",
    "reviewedHash": "8fc6d30d5a5e907d",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "bounds",
    "kind": "lesson",
    "reviewedHash": "d20d99c2f1843e9d",
    "reviewedAt": "2026-10-10",
    "batch": 3,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "bst-operations",
    "kind": "lesson",
    "reviewedHash": "d5cf50c46527978b",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "bubble-sort",
    "kind": "lesson",
    "reviewedHash": "4cf9f584f08ce225",
    "reviewedAt": "2026-10-10",
    "batch": 3,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "bucket-sort",
    "kind": "lesson",
    "reviewedHash": "6b22322e02d943f8",
    "reviewedAt": "2026-10-10",
    "batch": 3,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "caching-seen",
    "kind": "lesson",
    "reviewedHash": "e204707d577bcd02",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "cases",
    "kind": "lesson",
    "reviewedHash": "0a02e964bdeb39e7",
    "reviewedAt": "2026-10-05",
    "batch": 1
  },
  {
    "id": "classes",
    "kind": "lesson",
    "reviewedHash": "e57a6eba22fe7173",
    "reviewedAt": "2026-10-05",
    "batch": 1
  },
  {
    "id": "comparators",
    "kind": "lesson",
    "reviewedHash": "c596b71084ba6c82",
    "reviewedAt": "2026-10-10",
    "batch": 3,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "complexity",
    "kind": "lesson",
    "reviewedHash": "de74e7e7e0ad82d6",
    "reviewedAt": "2026-10-05",
    "batch": 1
  },
  {
    "id": "conditions",
    "kind": "lesson",
    "reviewedHash": "be2f2011ca4c5afe",
    "reviewedAt": "2026-10-05",
    "batch": 1
  },
  {
    "id": "connected-components",
    "kind": "lesson",
    "reviewedHash": "c85962fa5228cb99",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "correctness",
    "kind": "lesson",
    "reviewedHash": "944aeb240d2884f6",
    "reviewedAt": "2026-10-05",
    "batch": 1
  },
  {
    "id": "count-set-bits",
    "kind": "lesson",
    "reviewedHash": "e46e11de4715767e",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "counting-sort",
    "kind": "lesson",
    "reviewedHash": "c01803df042ffbb7",
    "reviewedAt": "2026-10-10",
    "batch": 3,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "dijkstra",
    "kind": "lesson",
    "reviewedHash": "ed13ace6af5f5374",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "dp-1d-2d",
    "kind": "lesson",
    "reviewedHash": "55c2b049bdd0409a",
    "reviewedAt": "2026-10-10",
    "batch": 6,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "dp-backtracking",
    "kind": "lesson",
    "reviewedHash": "73e310b733d34fff",
    "reviewedAt": "2026-10-10",
    "batch": 6,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "dp-base-cases",
    "kind": "lesson",
    "reviewedHash": "fd283b474bd68708",
    "reviewedAt": "2026-10-10",
    "batch": 6,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "dp-climbing-stairs",
    "kind": "lesson",
    "reviewedHash": "3bbd3beb135c5b15",
    "reviewedAt": "2026-10-10",
    "batch": 6,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "dp-coin-change",
    "kind": "lesson",
    "reviewedHash": "d0c4ce9fe7fa8ca2",
    "reviewedAt": "2026-10-10",
    "batch": 6,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "dp-combinations",
    "kind": "lesson",
    "reviewedHash": "f00d2ca1a2ef2bc9",
    "reviewedAt": "2026-10-10",
    "batch": 6,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "dp-divide-and-conquer",
    "kind": "lesson",
    "reviewedHash": "5805ae7a93140f75",
    "reviewedAt": "2026-10-10",
    "batch": 6,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "dp-grid-paths",
    "kind": "lesson",
    "reviewedHash": "4cd4e3652f3802d6",
    "reviewedAt": "2026-10-10",
    "batch": 6,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "dp-house-robber",
    "kind": "lesson",
    "reviewedHash": "d2308771d8c5c10d",
    "reviewedAt": "2026-10-10",
    "batch": 6,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "dp-knapsack",
    "kind": "lesson",
    "reviewedHash": "92f80a92b6ddc9fe",
    "reviewedAt": "2026-10-10",
    "batch": 6,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "dp-lcs",
    "kind": "lesson",
    "reviewedHash": "5fd89eac17d69daf",
    "reviewedAt": "2026-10-10",
    "batch": 6,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "dp-lis",
    "kind": "lesson",
    "reviewedHash": "44cd16b63e5d0caa",
    "reviewedAt": "2026-10-10",
    "batch": 6,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "dp-memoization",
    "kind": "lesson",
    "reviewedHash": "b1957733e9da47dd",
    "reviewedAt": "2026-10-10",
    "batch": 6,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "dp-n-queens",
    "kind": "lesson",
    "reviewedHash": "c043d5ebfcb009f3",
    "reviewedAt": "2026-10-10",
    "batch": 6,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "dp-permutations",
    "kind": "lesson",
    "reviewedHash": "ecc9a873462f66b2",
    "reviewedAt": "2026-10-10",
    "batch": 6,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "dp-recursive-calls",
    "kind": "lesson",
    "reviewedHash": "942ecb1a5bdd1406",
    "reviewedAt": "2026-10-10",
    "batch": 6,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "dp-state-transitions",
    "kind": "lesson",
    "reviewedHash": "52e41c4f20588a12",
    "reviewedAt": "2026-10-10",
    "batch": 6,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "dp-subsequences",
    "kind": "lesson",
    "reviewedHash": "a9d93f887df378a0",
    "reviewedAt": "2026-10-10",
    "batch": 6,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "dp-subsets",
    "kind": "lesson",
    "reviewedHash": "c0d4723aa0315815",
    "reviewedAt": "2026-10-10",
    "batch": 6,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "dp-tabulation",
    "kind": "lesson",
    "reviewedHash": "be88413378e189b9",
    "reviewedAt": "2026-10-10",
    "batch": 6,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "duplicate-detection",
    "kind": "lesson",
    "reviewedHash": "d7b5e75d70d57aed",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "errors",
    "kind": "lesson",
    "reviewedHash": "40378ecd5eb1e320",
    "reviewedAt": "2026-10-05",
    "batch": 1
  },
  {
    "id": "expression-evaluation",
    "kind": "lesson",
    "reviewedHash": "3135c836a61afdcd",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "expressions",
    "kind": "lesson",
    "reviewedHash": "32b82b97f920056f",
    "reviewedAt": "2026-10-05",
    "batch": 1
  },
  {
    "id": "fenwick-tree",
    "kind": "lesson",
    "reviewedHash": "cd3e4ca8333bc7a5",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "floyd-warshall",
    "kind": "lesson",
    "reviewedHash": "3e88a4a42cf0178c",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "functions",
    "kind": "lesson",
    "reviewedHash": "34076dce4cf0d3ba",
    "reviewedAt": "2026-10-05",
    "batch": 1
  },
  {
    "id": "graph-bfs",
    "kind": "lesson",
    "reviewedHash": "158618b140660aa6",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "graph-cycle-detection",
    "kind": "lesson",
    "reviewedHash": "f7ac50e7cb143b8f",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "graph-dfs",
    "kind": "lesson",
    "reviewedHash": "7e65de190951f31f",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "graph-representations",
    "kind": "lesson",
    "reviewedHash": "358da22f2b8aae98",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "grouping",
    "kind": "lesson",
    "reviewedHash": "2ecb0bfaec932a6b",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "hashing-frequency",
    "kind": "lesson",
    "reviewedHash": "d30d59dea192c2ea",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "heap-sift",
    "kind": "lesson",
    "reviewedHash": "6229334a1cf982c8",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "heap-sort",
    "kind": "lesson",
    "reviewedHash": "606b3a3dfb7bd69d",
    "reviewedAt": "2026-10-10",
    "batch": 3,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "in-place-modification",
    "kind": "lesson",
    "reviewedHash": "ffc709f8e3ce96fb",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "insertion-sort",
    "kind": "lesson",
    "reviewedHash": "977f5d7654950125",
    "reviewedAt": "2026-10-10",
    "batch": 3,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "interval-sorting",
    "kind": "lesson",
    "reviewedHash": "ae105415d3888208",
    "reviewedAt": "2026-10-10",
    "batch": 3,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "intervals",
    "kind": "lesson",
    "reviewedHash": "a1204be518ade3e7",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "io",
    "kind": "lesson",
    "reviewedHash": "c76bd4181538df89",
    "reviewedAt": "2026-10-05",
    "batch": 1
  },
  {
    "id": "kadane",
    "kind": "lesson",
    "reviewedHash": "a233d916247460a7",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "kmp",
    "kind": "lesson",
    "reviewedHash": "b6677b9b59c10ad5",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "kruskal",
    "kind": "lesson",
    "reviewedHash": "757c20a4dd94f9f2",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "kth-largest",
    "kind": "lesson",
    "reviewedHash": "7b64f0c65e9f9cca",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "linear-search",
    "kind": "lesson",
    "reviewedHash": "a237de12b615c1cd",
    "reviewedAt": "2026-10-10",
    "batch": 3,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "linked-list-cycle-detection",
    "kind": "lesson",
    "reviewedHash": "39d3b9278a1d42d4",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "linked-list-deques",
    "kind": "lesson",
    "reviewedHash": "6bb00cb0cf3326d3",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "linked-list-dummy-nodes",
    "kind": "lesson",
    "reviewedHash": "b180ab157478a517",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "linked-list-merging",
    "kind": "lesson",
    "reviewedHash": "e6305727a6e75f48",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "linked-list-middle",
    "kind": "lesson",
    "reviewedHash": "177fe06df5798e65",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "linked-list-pointer-manipulation",
    "kind": "lesson",
    "reviewedHash": "94d4075cc6df9487",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "linked-list-reversal",
    "kind": "lesson",
    "reviewedHash": "7b51b215363ffc9d",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "linked-list-slow-fast",
    "kind": "lesson",
    "reviewedHash": "d05f80d3a7da0d3c",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "linked-list-traversal",
    "kind": "lesson",
    "reviewedHash": "307bd234a6470b5f",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "linked-list-variants",
    "kind": "lesson",
    "reviewedHash": "693bb9bc61dbd682",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "loops",
    "kind": "lesson",
    "reviewedHash": "a25a71184fd4c0a1",
    "reviewedAt": "2026-10-10",
    "batch": 1,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "lowest-common-ancestor",
    "kind": "lesson",
    "reviewedHash": "335ee763bc93066d",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "maps-sets",
    "kind": "lesson",
    "reviewedHash": "b144574b388e816f",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "matrix-search",
    "kind": "lesson",
    "reviewedHash": "a49e1e80cc8b2c37",
    "reviewedAt": "2026-10-10",
    "batch": 3,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "matrix-traversal",
    "kind": "lesson",
    "reviewedHash": "a18bdb8bfddf195f",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "meeting-rooms-ii",
    "kind": "lesson",
    "reviewedHash": "866695c4805a26d6",
    "reviewedAt": "2026-10-10",
    "batch": 3,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "merge-sort",
    "kind": "lesson",
    "reviewedHash": "8ced05a58bac439d",
    "reviewedAt": "2026-10-10",
    "batch": 3,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "merge-sorted-data",
    "kind": "lesson",
    "reviewedHash": "f601c829a21cc276",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "min-max-heaps",
    "kind": "lesson",
    "reviewedHash": "6c21b6995b657143",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "min-max-tracking",
    "kind": "lesson",
    "reviewedHash": "d06b86e6c201924d",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "monotonic-stack",
    "kind": "lesson",
    "reviewedHash": "342be63760409f8d",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "multi-source-bfs",
    "kind": "lesson",
    "reviewedHash": "14146ab50bd23b4d",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "palindromes",
    "kind": "lesson",
    "reviewedHash": "8395ca2ac78c8bfd",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "parentheses-matching",
    "kind": "lesson",
    "reviewedHash": "2f08634792aab3fb",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "prefix-search",
    "kind": "lesson",
    "reviewedHash": "48d89750581c170e",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "prefix-sums",
    "kind": "lesson",
    "reviewedHash": "8d39720d4e7efcbc",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "prefix-sums-map",
    "kind": "lesson",
    "reviewedHash": "6c624c007c15dc40",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "prim",
    "kind": "lesson",
    "reviewedHash": "55a5e218c8627f60",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "quick-sort",
    "kind": "lesson",
    "reviewedHash": "1932b5f5c14baedf",
    "reviewedAt": "2026-10-10",
    "batch": 3,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "radix-sort",
    "kind": "lesson",
    "reviewedHash": "39fd7540066fcc7e",
    "reviewedAt": "2026-10-10",
    "batch": 3,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "references-mutation",
    "kind": "lesson",
    "reviewedHash": "5eeecfc8bcb206fd",
    "reviewedAt": "2026-10-05",
    "batch": 1
  },
  {
    "id": "representations",
    "kind": "lesson",
    "reviewedHash": "13848cb935af1779",
    "reviewedAt": "2026-10-05",
    "batch": 1
  },
  {
    "id": "rotated-array-search",
    "kind": "lesson",
    "reviewedHash": "4ae88a595d050c38",
    "reviewedAt": "2026-10-10",
    "batch": 3,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "running-median",
    "kind": "lesson",
    "reviewedHash": "59f4c4b71c7e01eb",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "scope",
    "kind": "lesson",
    "reviewedHash": "612ab2035b310049",
    "reviewedAt": "2026-10-05",
    "batch": 1
  },
  {
    "id": "segment-tree",
    "kind": "lesson",
    "reviewedHash": "fa3d8511fc0b1ca8",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "selection-sort",
    "kind": "lesson",
    "reviewedHash": "9adf456cd5519520",
    "reviewedAt": "2026-10-10",
    "batch": 3,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "shortest-paths-unweighted",
    "kind": "lesson",
    "reviewedHash": "24c5cc38b62191b2",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "sliding-window",
    "kind": "lesson",
    "reviewedHash": "617190ca5146555d",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "stack-queue-operations",
    "kind": "lesson",
    "reviewedHash": "7f379d26bcdf3751",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "string-frequency",
    "kind": "lesson",
    "reviewedHash": "6378ad9293f6eb22",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "string-parsing",
    "kind": "lesson",
    "reviewedHash": "5363bf6fc5194bf7",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "string-sliding-window",
    "kind": "lesson",
    "reviewedHash": "d901d2ce508ce111",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "string-two-pointers",
    "kind": "lesson",
    "reviewedHash": "2940595d02fe2042",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "substrings",
    "kind": "lesson",
    "reviewedHash": "f73d909defbe3956",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "task-scheduler",
    "kind": "lesson",
    "reviewedHash": "e406fabf9a8e5dc5",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "top-k",
    "kind": "lesson",
    "reviewedHash": "dbe40ceb7b86cc0f",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "topological-sort",
    "kind": "lesson",
    "reviewedHash": "8d35e103b81676bb",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "tree-bfs",
    "kind": "lesson",
    "reviewedHash": "e719eba1228698e7",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "tree-construction",
    "kind": "lesson",
    "reviewedHash": "a54955dd8b1c3402",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "tree-dfs",
    "kind": "lesson",
    "reviewedHash": "8c4bd50424c157e3",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "tree-height-depth",
    "kind": "lesson",
    "reviewedHash": "de8d80b85bdfbdb2",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "tree-traversals",
    "kind": "lesson",
    "reviewedHash": "f57cb28fc4eac982",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "trie-insertion",
    "kind": "lesson",
    "reviewedHash": "a0d882b93c8e53c5",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "two-heap-pattern",
    "kind": "lesson",
    "reviewedHash": "b085653b41869d2c",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "two-pointers",
    "kind": "lesson",
    "reviewedHash": "62f086c53ee27b63",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "union-find",
    "kind": "lesson",
    "reviewedHash": "f685346da91b8a96",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "value-to-index",
    "kind": "lesson",
    "reviewedHash": "03058a26153bdd0d",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "variables-and-types",
    "kind": "lesson",
    "reviewedHash": "612fac88ec9babef",
    "reviewedAt": "2026-10-04",
    "batch": 1
  },
  {
    "id": "word-search",
    "kind": "lesson",
    "reviewedHash": "745fc48ded2a7c80",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "xor-cancellation",
    "kind": "lesson",
    "reviewedHash": "41a8061f4973f924",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "backtracking",
    "kind": "pattern",
    "reviewedHash": "f83b6405b48aff4a",
    "reviewedAt": "2026-10-10",
    "batch": 6,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "bfs-shortest-path",
    "kind": "pattern",
    "reviewedHash": "cc87b16548600da8",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "binary-search-on-answer",
    "kind": "pattern",
    "reviewedHash": "bed466186b7cb844",
    "reviewedAt": "2026-10-10",
    "batch": 3,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "bitwise-xor",
    "kind": "pattern",
    "reviewedHash": "4251c634f6142710",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "cyclic-sort",
    "kind": "pattern",
    "reviewedHash": "76a032cae0856e32",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "dijkstra",
    "kind": "pattern",
    "reviewedHash": "216dd9045bd7bbb6",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "divide-and-conquer",
    "kind": "pattern",
    "reviewedHash": "042da46976f0fc39",
    "reviewedAt": "2026-10-10",
    "batch": 3,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "dynamic-programming",
    "kind": "pattern",
    "reviewedHash": "ae97e8b93df9e0a3",
    "reviewedAt": "2026-10-10",
    "batch": 6,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "fast-slow-pointers",
    "kind": "pattern",
    "reviewedHash": "6ecdb849e2629cc4",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "graph-dfs-components",
    "kind": "pattern",
    "reviewedHash": "1edb49a48caf29b5",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "greedy-interval-scheduling",
    "kind": "pattern",
    "reviewedHash": "e5cfd10d2b22c242",
    "reviewedAt": "2026-10-10",
    "batch": 3,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "in-place-linkedlist-reversal",
    "kind": "pattern",
    "reviewedHash": "b8cd8ab8a3d4253e",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "k-way-merge",
    "kind": "pattern",
    "reviewedHash": "4ddcbd3fa5647945",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "kadane",
    "kind": "pattern",
    "reviewedHash": "00f44dbdc6a1c10a",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "knapsack",
    "kind": "pattern",
    "reviewedHash": "7104d0599a0d5e38",
    "reviewedAt": "2026-10-10",
    "batch": 6,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "matrix-traversal",
    "kind": "pattern",
    "reviewedHash": "a3c74ba54ea38f82",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "merge-intervals",
    "kind": "pattern",
    "reviewedHash": "17fae99a8a79efa4",
    "reviewedAt": "2026-10-10",
    "batch": 3,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "modified-binary-search",
    "kind": "pattern",
    "reviewedHash": "22b5905b5840403c",
    "reviewedAt": "2026-10-10",
    "batch": 3,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "monotonic-stack",
    "kind": "pattern",
    "reviewedHash": "9fc6b611bc9d8161",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "prefix-sums-hashmap",
    "kind": "pattern",
    "reviewedHash": "aec635695aa06bcf",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "sliding-window",
    "kind": "pattern",
    "reviewedHash": "dc095fe23ec0561f",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "top-k-heap",
    "kind": "pattern",
    "reviewedHash": "6e915ecffb790b5f",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "topological-sort",
    "kind": "pattern",
    "reviewedHash": "54704d9a363f66f7",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "tree-bfs",
    "kind": "pattern",
    "reviewedHash": "a46d8158f33e2625",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "tree-dfs",
    "kind": "pattern",
    "reviewedHash": "b98d79459499ed4a",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "trie-prefix",
    "kind": "pattern",
    "reviewedHash": "557f3fb82e64a0c5",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "two-heaps",
    "kind": "pattern",
    "reviewedHash": "fa39fab4979b6ed0",
    "reviewedAt": "2026-10-10",
    "batch": 4,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "two-pointers",
    "kind": "pattern",
    "reviewedHash": "85dd9c69c2621a85",
    "reviewedAt": "2026-10-10",
    "batch": 2,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  },
  {
    "id": "union-find",
    "kind": "pattern",
    "reviewedHash": "d29f1056463de97b",
    "reviewedAt": "2026-10-10",
    "batch": 5,
    "reviewer": "Codex",
    "reviewerKind": "delegated-agent"
  }
];

/** Keyed by "<kind>:<id>" because a lesson and a pattern can share an id
 * (e.g. two-pointers, sliding-window, kadane, tree-dfs, dijkstra, ...). */
export const REVIEW_LEDGER_BY_KEY: Map<string, ReviewLedgerEntry> = new Map(
  REVIEW_LEDGER.map((e) => [e.kind + ":" + e.id, e]),
);
