/**
 * R5.3 — human semantic-review ledger (GENERATED by scripts/gen_review_ledger.mjs,
 * run deliberately by a human after re-reading the items).
 *
 * Each entry records that a person read this item's teaching content at the exact
 * `reviewedHash`. Evidence granting (codemod_add_evidence.mjs) sets
 * `evidence.semanticReview: true` ONLY when the item's CURRENT content hash
 * equals `reviewedHash` here — so a later content edit (which changes the hash)
 * makes semanticReview revert to pending until the item is re-read and this
 * ledger is regenerated. This is a RECORDED HUMAN CLAIM; the automated tests do
 * not "prove" the reading happened, they only enforce that a claim cannot outlive
 * the content it was made against.
 */
export interface ReviewLedgerEntry {
  id: string;
  kind: "lesson" | "pattern";
  /** contentHashOf(item) at the moment of human review. */
  reviewedHash: string;
  reviewedAt: string;
  /** R5.3 review batch (1-6). */
  batch: number;
}

export const REVIEW_LEDGER: ReviewLedgerEntry[] = [
  {
    "id": "adjacency-lists",
    "kind": "lesson",
    "reviewedHash": "acf53e74cf68e6c1",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "amortized",
    "kind": "lesson",
    "reviewedHash": "df41c96b0cd163e2",
    "reviewedAt": "2026-09-20",
    "batch": 1
  },
  {
    "id": "anagrams",
    "kind": "lesson",
    "reviewedHash": "97beb74ee9a56a67",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "array-traversal",
    "kind": "lesson",
    "reviewedHash": "a6683bf342da2d72",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "avl-rotations",
    "kind": "lesson",
    "reviewedHash": "bbcd62975022d36d",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "bellman-ford",
    "kind": "lesson",
    "reviewedHash": "f332f8640ae28309",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "bfs-queues",
    "kind": "lesson",
    "reviewedHash": "c7b585674290f9d4",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "binary-search",
    "kind": "lesson",
    "reviewedHash": "d21d0a0e796c9bee",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "binary-search-answer",
    "kind": "lesson",
    "reviewedHash": "12891e8de1aaae8b",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "bit-check-set-clear",
    "kind": "lesson",
    "reviewedHash": "aa2494271ae5faaa",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "bit-logical-ops",
    "kind": "lesson",
    "reviewedHash": "83dfb7176d0862bb",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "bit-shifts",
    "kind": "lesson",
    "reviewedHash": "57390a348f03f7e2",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "bounds",
    "kind": "lesson",
    "reviewedHash": "1716bd90dcb9bf8d",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "bst-operations",
    "kind": "lesson",
    "reviewedHash": "4d3da813c2e5a8e4",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "bubble-sort",
    "kind": "lesson",
    "reviewedHash": "15117d367ff3ea1f",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "bucket-sort",
    "kind": "lesson",
    "reviewedHash": "4ce22d75e5db9ed6",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "caching-seen",
    "kind": "lesson",
    "reviewedHash": "9d6a927bf0e5b46a",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "cases",
    "kind": "lesson",
    "reviewedHash": "1209e895786f399f",
    "reviewedAt": "2026-09-20",
    "batch": 1
  },
  {
    "id": "classes",
    "kind": "lesson",
    "reviewedHash": "7ad5c0b0b6d0c22f",
    "reviewedAt": "2026-09-20",
    "batch": 1
  },
  {
    "id": "comparators",
    "kind": "lesson",
    "reviewedHash": "c640669672b5c73f",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "complexity",
    "kind": "lesson",
    "reviewedHash": "82f8046bf5a953e3",
    "reviewedAt": "2026-09-20",
    "batch": 1
  },
  {
    "id": "conditions",
    "kind": "lesson",
    "reviewedHash": "dfc89aa5393f06da",
    "reviewedAt": "2026-09-20",
    "batch": 1
  },
  {
    "id": "connected-components",
    "kind": "lesson",
    "reviewedHash": "4f76bc47ed30a856",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "correctness",
    "kind": "lesson",
    "reviewedHash": "bbe19b60be936c65",
    "reviewedAt": "2026-09-20",
    "batch": 1
  },
  {
    "id": "count-set-bits",
    "kind": "lesson",
    "reviewedHash": "8fa5a5886bff758a",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "counting-sort",
    "kind": "lesson",
    "reviewedHash": "1f4e7ea019cc7533",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "dijkstra",
    "kind": "lesson",
    "reviewedHash": "fed7b9baec3e2464",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "dp-1d-2d",
    "kind": "lesson",
    "reviewedHash": "010df59c32e2771e",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-backtracking",
    "kind": "lesson",
    "reviewedHash": "cd588546b241553b",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-base-cases",
    "kind": "lesson",
    "reviewedHash": "e97f44ebd92612d7",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-climbing-stairs",
    "kind": "lesson",
    "reviewedHash": "c3b9b07d34ca592e",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-coin-change",
    "kind": "lesson",
    "reviewedHash": "490a600b4651693f",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-combinations",
    "kind": "lesson",
    "reviewedHash": "d8348c1f82ebf7c9",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-divide-and-conquer",
    "kind": "lesson",
    "reviewedHash": "00e75e6c611fc44b",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-grid-paths",
    "kind": "lesson",
    "reviewedHash": "4f7e05cac4c48fd1",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-house-robber",
    "kind": "lesson",
    "reviewedHash": "4770a85e88b0d403",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-knapsack",
    "kind": "lesson",
    "reviewedHash": "c77a488534b0dbdf",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-lcs",
    "kind": "lesson",
    "reviewedHash": "37cee5ef9dd92716",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-lis",
    "kind": "lesson",
    "reviewedHash": "24ce470bc7fc7510",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-memoization",
    "kind": "lesson",
    "reviewedHash": "080bdcb900a9f453",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-n-queens",
    "kind": "lesson",
    "reviewedHash": "15b3247eca96e9a0",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-permutations",
    "kind": "lesson",
    "reviewedHash": "939b89d03e8efe2c",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-recursive-calls",
    "kind": "lesson",
    "reviewedHash": "d266e7b616b7c900",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-state-transitions",
    "kind": "lesson",
    "reviewedHash": "6b8bf29b7a8008fb",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-subsequences",
    "kind": "lesson",
    "reviewedHash": "4502c3b49c252a77",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-subsets",
    "kind": "lesson",
    "reviewedHash": "ac7949d9001b72dd",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "dp-tabulation",
    "kind": "lesson",
    "reviewedHash": "2d202287c95a1993",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "duplicate-detection",
    "kind": "lesson",
    "reviewedHash": "230037c80a8b7f76",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "errors",
    "kind": "lesson",
    "reviewedHash": "935f03e64e7a8423",
    "reviewedAt": "2026-09-20",
    "batch": 1
  },
  {
    "id": "expression-evaluation",
    "kind": "lesson",
    "reviewedHash": "562a44ce56ec57fd",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "expressions",
    "kind": "lesson",
    "reviewedHash": "0031a9400b72ef46",
    "reviewedAt": "2026-09-20",
    "batch": 1
  },
  {
    "id": "fenwick-tree",
    "kind": "lesson",
    "reviewedHash": "8cd9c596dba9c38c",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "floyd-warshall",
    "kind": "lesson",
    "reviewedHash": "0054644f6ce1b021",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "functions",
    "kind": "lesson",
    "reviewedHash": "8a4cf399be4cfaa9",
    "reviewedAt": "2026-09-20",
    "batch": 1
  },
  {
    "id": "graph-bfs",
    "kind": "lesson",
    "reviewedHash": "382e88786482a4ab",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "graph-cycle-detection",
    "kind": "lesson",
    "reviewedHash": "fb9a0abc24bacb9b",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "graph-dfs",
    "kind": "lesson",
    "reviewedHash": "53e5fcf1bd53b057",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "graph-representations",
    "kind": "lesson",
    "reviewedHash": "7d1fbf4143bcbf7d",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "grouping",
    "kind": "lesson",
    "reviewedHash": "737cf029a3a7afa3",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "hashing-frequency",
    "kind": "lesson",
    "reviewedHash": "919f88fdbd87b5af",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "heap-sift",
    "kind": "lesson",
    "reviewedHash": "661843ab16264d08",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "heap-sort",
    "kind": "lesson",
    "reviewedHash": "19e3fad50a51dfd5",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "in-place-modification",
    "kind": "lesson",
    "reviewedHash": "d8f67eacc96b75e2",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "insertion-sort",
    "kind": "lesson",
    "reviewedHash": "f3ec2e8f7473cd6a",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "interval-sorting",
    "kind": "lesson",
    "reviewedHash": "49724a8fb9f03e24",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "intervals",
    "kind": "lesson",
    "reviewedHash": "dd19cbd5f67b20d0",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "io",
    "kind": "lesson",
    "reviewedHash": "0c34394abcb68771",
    "reviewedAt": "2026-09-20",
    "batch": 1
  },
  {
    "id": "kadane",
    "kind": "lesson",
    "reviewedHash": "ac44661c3fb5bc41",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "kmp",
    "kind": "lesson",
    "reviewedHash": "eac8660e504ddee6",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "kruskal",
    "kind": "lesson",
    "reviewedHash": "72dc25240000bb2b",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "kth-largest",
    "kind": "lesson",
    "reviewedHash": "26a1e3942362c56d",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "linear-search",
    "kind": "lesson",
    "reviewedHash": "c99b9daa622305fd",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "linked-list-cycle-detection",
    "kind": "lesson",
    "reviewedHash": "215b87bdeace9f0b",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "linked-list-deques",
    "kind": "lesson",
    "reviewedHash": "0d245a88161095ab",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "linked-list-dummy-nodes",
    "kind": "lesson",
    "reviewedHash": "d2a7e4a1cc56afba",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "linked-list-merging",
    "kind": "lesson",
    "reviewedHash": "61896f0e4aa70951",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "linked-list-middle",
    "kind": "lesson",
    "reviewedHash": "e796e46510cc0078",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "linked-list-pointer-manipulation",
    "kind": "lesson",
    "reviewedHash": "fd320af46eb9c09e",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "linked-list-reversal",
    "kind": "lesson",
    "reviewedHash": "ec9e65ff7a3d42ff",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "linked-list-slow-fast",
    "kind": "lesson",
    "reviewedHash": "3b1198567adc22b0",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "linked-list-traversal",
    "kind": "lesson",
    "reviewedHash": "a83276a2f18bd51c",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "linked-list-variants",
    "kind": "lesson",
    "reviewedHash": "930cee5b8ff7a9ad",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "loops",
    "kind": "lesson",
    "reviewedHash": "8652678e5497d9c4",
    "reviewedAt": "2026-09-20",
    "batch": 1
  },
  {
    "id": "lowest-common-ancestor",
    "kind": "lesson",
    "reviewedHash": "8fa7d7ce6ae0a3ca",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "maps-sets",
    "kind": "lesson",
    "reviewedHash": "4f48d5c53a071da7",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "matrix-search",
    "kind": "lesson",
    "reviewedHash": "1344987a074e5df0",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "matrix-traversal",
    "kind": "lesson",
    "reviewedHash": "0706cb68dea95a7a",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "merge-sort",
    "kind": "lesson",
    "reviewedHash": "f6de8048ab5d8d89",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "merge-sorted-data",
    "kind": "lesson",
    "reviewedHash": "7c6cb70710713bc5",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "min-max-heaps",
    "kind": "lesson",
    "reviewedHash": "29ace62fcb4adc2d",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "min-max-tracking",
    "kind": "lesson",
    "reviewedHash": "3919ac49b17bad05",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "monotonic-stack",
    "kind": "lesson",
    "reviewedHash": "5ca8e54606f871f9",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "multi-source-bfs",
    "kind": "lesson",
    "reviewedHash": "c96edf1aa43e6cc3",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "palindromes",
    "kind": "lesson",
    "reviewedHash": "95071746a9dc61f6",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "parentheses-matching",
    "kind": "lesson",
    "reviewedHash": "d0fc1e6b9db9b427",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "prefix-search",
    "kind": "lesson",
    "reviewedHash": "175bba019a175975",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "prefix-sums",
    "kind": "lesson",
    "reviewedHash": "fc196b7aeb3fab57",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "prefix-sums-map",
    "kind": "lesson",
    "reviewedHash": "57a9438955b80cea",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "prim",
    "kind": "lesson",
    "reviewedHash": "7b95bb3d8a19af4c",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "quick-sort",
    "kind": "lesson",
    "reviewedHash": "e310478b9e80e5b9",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "radix-sort",
    "kind": "lesson",
    "reviewedHash": "a92f35299a603e37",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "references-mutation",
    "kind": "lesson",
    "reviewedHash": "0237324213b22cc2",
    "reviewedAt": "2026-09-20",
    "batch": 1
  },
  {
    "id": "representations",
    "kind": "lesson",
    "reviewedHash": "234fdd7bef71bb6e",
    "reviewedAt": "2026-09-20",
    "batch": 1
  },
  {
    "id": "rotated-array-search",
    "kind": "lesson",
    "reviewedHash": "12bfcc593bb15c8a",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "running-median",
    "kind": "lesson",
    "reviewedHash": "751ae8ae83b298db",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "scope",
    "kind": "lesson",
    "reviewedHash": "35f184459c464a8b",
    "reviewedAt": "2026-09-20",
    "batch": 1
  },
  {
    "id": "segment-tree",
    "kind": "lesson",
    "reviewedHash": "37ccd62898f3b611",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "selection-sort",
    "kind": "lesson",
    "reviewedHash": "d705f40e376781b1",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "shortest-paths-unweighted",
    "kind": "lesson",
    "reviewedHash": "e18032f91ae15e60",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "sliding-window",
    "kind": "lesson",
    "reviewedHash": "25ad7561287d0a04",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "stack-queue-operations",
    "kind": "lesson",
    "reviewedHash": "8c4637f0b9e6b67c",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "string-frequency",
    "kind": "lesson",
    "reviewedHash": "2689a28ccd8cbdf2",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "string-parsing",
    "kind": "lesson",
    "reviewedHash": "64a5b2cab101bb4a",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "string-sliding-window",
    "kind": "lesson",
    "reviewedHash": "305dfbb81644ed5c",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "string-two-pointers",
    "kind": "lesson",
    "reviewedHash": "0c5053ccf16d1910",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "substrings",
    "kind": "lesson",
    "reviewedHash": "7ef2dc4db9e7a9fb",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "top-k",
    "kind": "lesson",
    "reviewedHash": "5f680c436688f8ae",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "topological-sort",
    "kind": "lesson",
    "reviewedHash": "5959887f6a3ab874",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "tree-bfs",
    "kind": "lesson",
    "reviewedHash": "d892bd09e285ca0f",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "tree-construction",
    "kind": "lesson",
    "reviewedHash": "e319428dc111a302",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "tree-dfs",
    "kind": "lesson",
    "reviewedHash": "60e56c2ba1437bc8",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "tree-height-depth",
    "kind": "lesson",
    "reviewedHash": "7a42a58ae3c9f40f",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "tree-traversals",
    "kind": "lesson",
    "reviewedHash": "05ecbe9184642e1c",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "trie-insertion",
    "kind": "lesson",
    "reviewedHash": "f8bdff7320763ae1",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "two-heap-pattern",
    "kind": "lesson",
    "reviewedHash": "a68b17d8ed2109fb",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "two-pointers",
    "kind": "lesson",
    "reviewedHash": "f3ef9a86ea18c1d1",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "union-find",
    "kind": "lesson",
    "reviewedHash": "e64199d6c689f591",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "value-to-index",
    "kind": "lesson",
    "reviewedHash": "b4be939b638390e5",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "variables-and-types",
    "kind": "lesson",
    "reviewedHash": "8d39aed16bb15697",
    "reviewedAt": "2026-09-20",
    "batch": 1
  },
  {
    "id": "word-search",
    "kind": "lesson",
    "reviewedHash": "d20741b6c70583e8",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "xor-cancellation",
    "kind": "lesson",
    "reviewedHash": "f304c8a310a0312e",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "backtracking",
    "kind": "pattern",
    "reviewedHash": "badc11b260c89c05",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "bfs-shortest-path",
    "kind": "pattern",
    "reviewedHash": "5234cd0650af5b6f",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "binary-search-on-answer",
    "kind": "pattern",
    "reviewedHash": "47cff2f026433ea9",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "bitwise-xor",
    "kind": "pattern",
    "reviewedHash": "c3595172baff811b",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "cyclic-sort",
    "kind": "pattern",
    "reviewedHash": "d2fd863554d64d88",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "dijkstra",
    "kind": "pattern",
    "reviewedHash": "1c1203240fbc86b8",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "divide-and-conquer",
    "kind": "pattern",
    "reviewedHash": "166f5a5629254054",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "dynamic-programming",
    "kind": "pattern",
    "reviewedHash": "6c9173ebc66b7c96",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "fast-slow-pointers",
    "kind": "pattern",
    "reviewedHash": "425433b5f53ab15b",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "graph-dfs-components",
    "kind": "pattern",
    "reviewedHash": "ffcc920d66558bc2",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "greedy-interval-scheduling",
    "kind": "pattern",
    "reviewedHash": "109a0d7da8b51689",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "in-place-linkedlist-reversal",
    "kind": "pattern",
    "reviewedHash": "a36c98667b7f633c",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "k-way-merge",
    "kind": "pattern",
    "reviewedHash": "af13a4e570af8b27",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "kadane",
    "kind": "pattern",
    "reviewedHash": "2f4bdf4bdc3a5307",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "knapsack",
    "kind": "pattern",
    "reviewedHash": "d94fa36ddbc91839",
    "reviewedAt": "2026-09-20",
    "batch": 6
  },
  {
    "id": "matrix-traversal",
    "kind": "pattern",
    "reviewedHash": "53ed4fa3a5771257",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "merge-intervals",
    "kind": "pattern",
    "reviewedHash": "a4b44c093ede17e4",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "modified-binary-search",
    "kind": "pattern",
    "reviewedHash": "199e2189f6d57d0b",
    "reviewedAt": "2026-09-20",
    "batch": 3
  },
  {
    "id": "monotonic-stack",
    "kind": "pattern",
    "reviewedHash": "819741f643ed2285",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "prefix-sums-hashmap",
    "kind": "pattern",
    "reviewedHash": "cc9c58251e7081ba",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "sliding-window",
    "kind": "pattern",
    "reviewedHash": "78b424d3a1cb8d6d",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "top-k-heap",
    "kind": "pattern",
    "reviewedHash": "555d2446c2cddc97",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "topological-sort",
    "kind": "pattern",
    "reviewedHash": "294aa2301a17661b",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "tree-bfs",
    "kind": "pattern",
    "reviewedHash": "93333da7d410c7ab",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "tree-dfs",
    "kind": "pattern",
    "reviewedHash": "d7df312529da2294",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "trie-prefix",
    "kind": "pattern",
    "reviewedHash": "ce366fef2a20542b",
    "reviewedAt": "2026-09-20",
    "batch": 5
  },
  {
    "id": "two-heaps",
    "kind": "pattern",
    "reviewedHash": "cb75838b74c6ac49",
    "reviewedAt": "2026-09-20",
    "batch": 4
  },
  {
    "id": "two-pointers",
    "kind": "pattern",
    "reviewedHash": "c2de5e2be9b19faf",
    "reviewedAt": "2026-09-20",
    "batch": 2
  },
  {
    "id": "union-find",
    "kind": "pattern",
    "reviewedHash": "9b0e0c1338468ab7",
    "reviewedAt": "2026-09-20",
    "batch": 5
  }
];

/** Keyed by "<kind>:<id>" because a lesson and a pattern can share an id
 * (e.g. two-pointers, sliding-window, kadane, tree-dfs, dijkstra, ...). */
export const REVIEW_LEDGER_BY_KEY: Map<string, ReviewLedgerEntry> = new Map(
  REVIEW_LEDGER.map((e) => [e.kind + ":" + e.id, e]),
);
